Support IAM permissions boundaries
rhythmictech/terraform-aws-efs-filesystem pull request #11
Opened 2021-10-08 21:43 UTC by joshbeard

This adds support for specifying an IAM permissions boundary when
creating the IAM role for backups. It defaults to `null`, so it
is backwards-compatible.

* https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.htm
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_role#permissions_boundary

2021-10-22 23:58 UTC, sblack4 requested changes

2021-10-22 23:58 UTC, sblack4 commented on backup.tf
> +  kms_key_arn               = local.create_backup_kms_key ? aws_kms_key.backup[0].arn : var.backup_kms_key_id
plz run `terraform fmt` <3

2021-12-06 19:44 UTC, joshbeard commented
@sblack4 Sorry for the pause on this - real life stuff. I used the included pre-commit config here, rebased, and pushed the changes. Should be good to go now. Long variable name, but I was trying to stay consistent ;)

2021-12-06 20:01 UTC, sblack4 approved these changes

2021-12-06 20:02 UTC, merged